name: whyamisotired
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37714043934829533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120e0b'
    - '#f2c3a7'
    - '#8e7ac2'
    - '#f13239'
    - '#6fe577'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
