name: whyamisotired
favicon: null
layout_spectrum: 0.25226
typography_spectrum: 0.15111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120e0b'
    - '#f2c3a7'
    - '#8e7ac2'
    - '#f13239'
    - '#6fe577'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
